### ISSUE TITLE
Should JuliaHEP be on the Julia Organisations page?

### ISSUE THREAD

**Issue by aoanla** [JuliaHEP/www.juliahep.org#7]
https://julialang.org/community/organizations/ has many GitHub organisations that are Julia-oriented, but JuliaHEP is missing....

(There's no way to raise a "Org Issue" so I raised here as it's sort of "webby")

**Comment by Moelf** [comment]
You can make a PR to try to add it: https://github.com/JuliaLang/www.julialang.org/blob/main/community/organizations.md

**Comment by aoanla** [comment]
Sure, this issue was to check we agreed we *should* be on it, before I did the PR

**Comment by Moelf** [comment]
I don't have a strong opinion

**Comment by aoanla** [comment]
Well, I put in a PR: https://github.com/JuliaLang/www.julialang.org/pull/1965 so anyone who opposes feel free to comment there!

**Comment by LilithHafner** [comment]
Merged—this can be closed
